EXPENSE_CATEGORIES = [
    'Housing',
    'Transportation',
    'Groceries',
    'Utilities',
    'Healthcare',
    'Accommodation',
    'Debt Repayment',
    'Entertainment',
    'Personal Care',
    'Education',
    'Insurance',
    'Taxes',
    'Savings',
    'Miscellaneous',
    'Travel',
    'Home Maintenance',
    'Investments',
    'Clothing',
    'Dining Out',
    'Fitness',
    'Food',
    'Business',
    'My Girl',
    'Family',
    'Other',
]